# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: MISOMIP
email: 
description: > # this means to ignore newlines until "baseurl:"
  Marine Ice Sheet Ocean Model Intercomnparison Project
baseurl: "" # the subpath of your site, e.g. /blog
url: http://misomip.github.io/
github_username:  misomip
header-img: img/baniere.png

# Build settings
markdown: kramdown
permalink: pretty
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
